# Generated by Django 5.1 on 2024-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('selection', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('lifetime', 'Lifetime')], max_length=10)),
                ('nationality', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
